config/routes.rb
Rails.application.routes.draw do
  
  devise_for :user2s
  resources :comments
  devise_for :users
  
  resources :artistuploads
  resources :users
  

   root 'static_pages#index'

   get '/about' => 'static_pages#about'
   get '/careers' => 'static_pages#careers'
   get '/learnmore' => 'static_pages#learn_more'
   get '/home' => 'static_pages#index'

end

app/models/artistupload.rb
class Artistupload < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100#", :large => "800x800>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :title, :presence => :true
	validates :inspiration, :presence => { :message => "Sorry, But we'd like to know what inspired you."}
	validates :description, :presence => { :message => "You Must Add a Description!" }

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :artistuploads


end

app/models/user2.rb
class User2 < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :email, :first_name, :last_name, :username, :birthday, :about, :password, :remember_me)}
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:avatar, :first_name, :last_name, :username, :birthday, :email, :password, :remember_me)}
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit( :email, :password, :remember_me)}
  end
end

app/controllers/artistuploads_controller.rb
class ArtistuploadsController < ApplicationController
  before_action :set_artistupload, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /artistuploads
  # GET /artistuploads.json
  def index
    @artistuploads = Artistupload.all
  end

  # GET /artistuploads/1
  # GET /artistuploads/1.json
  def show
     

  end

  # GET /artistuploads/new
  def new
    @artistupload = current_user.artistuploads.build
  end

  # GET /artistuploads/1/edit
  def edit
  end

  # POST /artistuploads
  # POST /artistuploads.json
  def create
    @artistupload = current_user.artistuploads.build(artistupload_params)

    respond_to do |format|
      if @artistupload.save
        format.html { redirect_to @artistupload, notice: 'Artistupload was successfully created.' }
        format.json { render :show, status: :created, location: @artistupload }
      else
        format.html { render :new }
        format.json { render json: @artistupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artistuploads/1
  # PATCH/PUT /artistuploads/1.json
  def update
    respond_to do |format|
      if @artistupload.update(artistupload_params)
        format.html { redirect_to @artistupload, notice: 'Artistupload was successfully updated.' }
        format.json { render :show, status: :ok, location: @artistupload }
      else
        format.html { render :edit }
        format.json { render json: @artistupload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artistuploads/1
  # DELETE /artistuploads/1.json
  def destroy
    @artistupload.destroy
    respond_to do |format|
      format.html { redirect_to artistuploads_url, notice: 'Artistupload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artistupload
      @artistupload = Artistupload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artistupload_params
      params.require(:artistupload).permit(:title, :inspiration, :description, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 def home
 	@user = User.all
 	
 end

 def about
 	@user = User.all
 	
 	
 end

 def career_oppourtunities
 	
 end

 def learn_more
 	@user = User.all
 end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
 	@user = User.find(params[:id])
 	@user_artistuploads = @user.artistuploads
  end

  def index
  	@user = User.all
  	

  end

  def edit

  end

  def create 
  	@user = User.create( user_params )
  end

  private 

  def user_params
  		params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_uploads_helper.rb
module ArtistUploadsHelper
end

app/helpers/artistuploads_helper.rb
module ArtistuploadsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artistuploads/_form.html.erb
<%= simple_form_for(@artistupload) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.file_field :image %>
    <%= f.input :title %>
    <%= f.input :inspiration %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artistuploads/edit.html.erb
<h1 class="roboto">Editing Artistupload</h1>

<%= render 'form' %>

<%= link_to 'Show', @artistupload %> |
<%= link_to 'Back', artistuploads_path %>

app/views/artistuploads/index.html.erb
<div class="blackbox animated fadeOut"></div>
<div class="jumbotron customheight overlay shadow">
  <div class="container" style="padding-top:80px;">
    <p class ="roboto" id="notice"><%= notice %></p>

    <h1 class="roboto"><span style=" font-size: 45px; margin-right:15px; color: #FCC72C;"class="glyphicon glyphicon-send"></span>Artist Uploads</h1>
    <h4 class="roboto">The Latest & Greatest, From our Artists.</h4>
    <% if user_signed_in? %>
      <btn class="btn btn-primary">Add New Artwork</btn>
    <% else %>
      <btn class="btn btn-primary">Sign Up </btn>
      <btn class="btn btn-primary">Log In</btn>
    <% end %>
  </div>
</div>
<br>
<section class="container-fluid text-center">
  <div class="container">
  <img style="width:auto; height:100px; margin-left:auto; margin-right:auto" class=" img img-responsive" src="/assets/postcardcologofix.png" />
    <h1 class="roboto">Want To Become One Of Our Artists?</h1>
    
    <h4 class="monter">Get <b class="yellow">Paid</b> to <b>create</b> now with POST Card Co!</h4></div>
    <h6 class="text-muted">Learn about earning money while contributing as a postcardco artist.</h6>

    <br>
    <button class="btn btn-primary btn-lg roboto">
      Learn More
    </button>
    <hr>
  </div>
</section>
<div class="container-fluid">
<h5 class="roboto text-muted">There Are <b><%= @artistuploads.count %></b> Uploads and Counting! <b class="yellow">Join The Community!</b></h5><hr>
<% @artistuploads.each_slice(4) do |row| %>
  <div class="row"> <!-- Each row of my Grid -->
  <% row.each do |artistupload| %>
    <!-- Each item in my grids row -->
    <div class="col-sm-4 col-md-3">
    <div class="panel panel-default someclass shadow">
    <div class="panel-heading">
      <h3 class="roboto"><%= artistupload.title.titleize %></h3>
      
      <h6 class="text-muted"><span class="glyphicon glyphicon-user yellow" style="margin-right:5px;"></span><%= artistupload.user.first_name.titleize %> <%= artistupload.user.last_name.titleize%><small class=" text-muted pull-right">date</small></h6>

      </div>

    <div class="panel-body panel-custom">
      
      
      <%= image_tag artistupload.image.url(:medium), :class => 'img img-responsive full-width' %>
      <span class="glyphicon glyphicon-heart-empty textshadow"></span>
      <span class="glyphicon glyphicon-thumbs-up textshadow"></span>
      <span class="glyphicon glyphicon-thumbs-down textshadow"></span>
      <span class="glyphicon glyphicon-eye-open textshadow"></span>
      <br>
      <% if user_signed_in? %>
        <div class="container-fluid">
          <button class="btn btn-primary" style="width:100%">
            <span class="glyphicon glyphicon-plus"></span>
              Add To My Cards
          </button>
          <button class="btn btn-primary" style="width:100%; margin-bottom:10px; margin-top:10px">
            <span class="glyphicon glyphicon-pencil"></span>
              Edit This Card
          </button>
        </div>
      <% else %>
      <h6 class="text-muted"> You Are Not signed in. </h1>
      <% end %>
        
        <%= link_to 'Show', artistupload %>
        <%= link_to 'Edit', edit_artistupload_path(artistupload) %>
        <%= link_to 'Destroy', artistupload, method: :delete, data: { confirm: 'Are you sure?' } %>
     
</div>
</div>
    </div>

  <% end %>
  </div>
<% end %>



<br>

<%= link_to 'New Artistupload', new_artistupload_path, :class => 'btn btn-primary' %>

<hr>
</div>



<script>
  $(document).ready(function(){
    $(".blackbox").fadeOut(500);
    
  });

</script>

app/views/artistuploads/new.html.erb
<div class="video-bg overlay">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12">
			<div class="max-width" style="margin-top:100px;">
				<div class="panel panel-default shadow"> 
					<div class="panel-heading"> 
						<h1 class="roboto">New Artistupload</h1>

					</div>



					<div class="panel-body">
						<%= render 'form' %>

						<%= link_to 'Back', artistuploads_path %>

					</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/artistuploads/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container" style="margin-top:50px;">
	<div class="row">
		<div class="col-sm-8">
			<div class="panel panel-default shadow">
			<div class="panel-heading">
				<h1 class="roboto"><%=@artistupload.title.titleize %></h1>
				<h6><span class="text-muted">Artwork By</span> <%= @artistupload.user.first_name.titleize %> <%= @artistupload.user.last_name.titleize %></h6></div>
				<div class="panel-body">
				<%= image_tag @artistupload.image.url(:large), :class => 'img img-responsive' %><br>
				<span style="margin-right:7px; font-size:25px; margin-bottom:15px;" class="glyphicon glyphicon-thumbs-up"></span>
				<span style="margin-right:7px; font-size:25px;" class="glyphicon glyphicon-thumbs-down"></span>
				<span style="margin-right:7px; font-size:25px;" class="glyphicon glyphicon-eye-open"></span><br>
				<p><%= @artistupload.description %></p>
				</div>
			</div>

			
		</div>
		<div class="col-sm-4">
			<div class="panel panel-default shadow">
				<div class="panel-heading"><h5>Artwork Stats</h5></div>
				<div class="panel-body">
					<span class="glyphicon glyphicon-eye-open"></span><br>
					<span class="glyphicon glyphicon-heart-empty"></span><br>
					<span class="glyphicon glyphicon-thumbs-up"></span><br>
					<span class="glyphicon glyphicon-thumbs-down"></span><br>
					

				</div>

			</div>
			<div class="panel panel-default shadow">
				<div class="panel-heading"><h5>More About This Piece</h5></div>
				<div class="panel-body">
					<h6 class="text-muted">Description</h6>
					<p><%= @artistupload.description %></p>

				</div>

			</div>




		</div>


	</div>



	<hr>

	<%= link_to 'Edit', edit_artistupload_path(@artistupload) %> |
	<%= link_to 'Back', artistuploads_path %>

	<hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postcardcor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="favicon.ico">

  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,300' rel='stylesheet' type='text/css'>
  
  <!-- Animate.css -->
  <link rel="stylesheet" href="css/animate.css">
  <!-- Icomoon Icon Fonts-->
  <link rel="stylesheet" href="css/icomoon.css">
  <!-- Bootstrap  -->
  <link rel="stylesheet" href="css/bootstrap.css">
  <!-- Superfish -->
  <link rel="stylesheet" href="css/superfish.css">

  <link rel="stylesheet" href="css/style.css">


  <!-- Modernizr JS -->
  <script src="js/modernizr-2.6.2.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'POST Card Co', root_path, :class => 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Explore', '/artistuploads' %></li>
            <li><%= link_to 'Create', "/about" %></li>
            <li><a><span class="glyphicon glyphicon-search"></span></a></li>
            
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
            <% if user_signed_in? %>
            <li><a><span class="glyphicon glyphicon-send"></span></a></li>
            <li><a><span class="glyphicon glyphicon-envelope"></span></a></li>
            <li><a><span class="glyphicon glyphicon-globe"></span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" style="margin-right:5px;"></span><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">
					<li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
					<li><%= link_to 'Account Settings', edit_user_registration_path %></li>
					<li><%= link_to 'profile', current_user %></li>
                </ul>
                </li>
             <% else %>
             	<li><%= link_to 'Sign In', new_user_session_path %></li>
             	<li>
                <div style="margin-top:7px;">
                 <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-custom' %></btn>
                </div>
              </li>
             <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



	<%= yield %>

<footer>
      <div id="footer">
        <div class="container">
          <div class="row">
          <img style="width:auto; height:200px; margin-left:auto; margin-right:auto" class=" img-responsive text-center" src="/assets/postcardcologofix.png" />
            <div class="col-md-6 col-md-offset-3 text-center">
              
              <h6>Copyright 2016 <a href="#">POST Card Co</a>.<br> <b class="text-muted">Mail is for the birds post is for the people </b> <br> All Rights Reserved.</h6> 
            </div>
          </div>
        </div>
      </div>
      


<script>
  
  
  
  $(document).ready(function(){

  
    
    
   
    $(".blackbox").fadeOut(500);


      
    $(window).scroll(function(){
      if ( $(window).scrollTop() > 60 ) {
          $('.navbar-inverse').css('background-color', '#222831');
          $('.navbar-inverse').addClass('shadow');
        } else {
          $('.navbar-inverse').css("background-color", "transparent");
          $('.navbar-inverse').removeClass('shadow');
        };
    
    });
    
  });



    

    

    
</script>
</body>
</html>

app/views/static_pages/about.html.erb
<div style="max-height:1300px; min-height:100vh; background-color:white;" class="overlay">
	<div class="container">
		<div style=" margin-top:20vh; margin-left:auto; margin-right:auto; max-width:700px; padding-left:5px; padding-right:5px;">
			<div class="row">
			
				<h4 class="monter text-left" style="color:gray;"><span style="margin-top:4px; color: #FCC72C;margin-right:5px" class="glyphicon glyphicon-send"></span> ABOUT US</h4><hr>
				<p style="line-height:40px;"><b>POST</b> is a little idea with a <b>big</b> future- quite simply we make cards, greeting cards! We want to make the entire card buying process more convenient and personal than ever. The days of wandering lost in the supermarket searching for the perfect card are behind us. <b>POST</b> is here to make your experience fun, easy and nostalgic utilizing the Pony Express just like the good ole days.
				<br>
				<br>
				<b>Curated</b> by your young brilliant minds, we are seeking out the best designers, developers, and investors to bring our environmentally friendly idea to life. If you fit the bill, or to find out more, drop us a line. 
				<br>
				<br>
				Every card that is sold supports the independent artist who created the masterpiece.  Printed on organic Banana Paper, from EcoPaper, allows for an  earth friendly greeting card.
</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/careers.html.erb
<div class="jumbotron overlay" style="height:400px; padding-top:150px;">
	<div class="container" >
		<h1 class="monter" style="color:white">Career Oppourtunities</h1>
		<h4 class="text-muted">Seeking Young, <b>Bright</b> minds.</h4>
	</div>
</div>

<div class="container">
<div class="row">
	<div class="col-sm-3">
		<div class="panel panel-default shadow">
			<div class="panel-heading"><h5 class="roboto"><span class="glyphicon glyphicon-globe"></span><b>Navigate</b></h5></div>
			<div class="panel-body"></div>
		</div>

	</div>
	<div class="col-sm-9">
	<ol class="breadcrumb" style="font-size:15px;">
  		<li><a href="#">Home</a></li>
  		<li class="active">Career Oppourtunities</li>
	</ol>
	<h3 class="monter">What We're Looking For</h3>

	<p style="line-height:25px; text-indent:25px">Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. Vice biodiesel artisan, bushwick tofu austin polaroid pop-up meh small batch PBR&B ethical blog.</p>
	<p style="line-height:25px; text-indent:25px">Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. Vice biodiesel artisan, bushwick tofu austin polaroid pop-up meh small batch PBR&B ethical blog.</p>
	<hr>
	<h1 class="monter">Junior Developer </h1>
	<hr>
	<h3 class="roboto">As a Post Card Co <b class="text-muted">Junior Developer</b>, An Applicant Should Know</h3>
	<br>
	<ul>
		<li>Intermediate Javascript</li>
		<li>Familiar With Jquery</li>
		<li>Proficient With Ruby</li>
		<li>Proficient With Ruby On Rails (Webb Application Framework)</li>
		<li>Must Know Advanced HTML5 + CSS3</li>
	</ul>
	<br>
	<p> As a possible Applicant for <b>Post Card Co</b>, We are looking for <b>Developers</b> who are able to problem solve, and grow with us not only as a company, but as a brand. The Developers play a vital role in the company, because it is they (the developers) who help deliver the product and and influence the user's workflow when purchasing a card. 
</div>
</div>
	</div>

<div class="overlay" style="background: linear-gradient(141deg, #0fb8ad 0%, #1fc8db 51%, #2cb5e8 75%); height:auto; width:100%; padding-top:35px; padding-bottom:30px;">
	<div class="container text-center">
		
		<h1 class="roboto" style="color:white">Think you have what it takes? <span>Send Us Your Resume</span></h1>
		<h6>Subheading goes herer</h6>
		<br>
		<div class="row">
			<div class="col-sm-4">
				<h6><span class="glyphicon glyphicon-envelope"></span> <b>Developers@PostCardCo.com</b></h6>
			</div>
			<div class="col-sm-4">
				<h6><span class="glyphicon glyphicon-phone"></span> <b>Developers@PostCardCo.com</b></h6>
			</div>
			<div class="col-sm-4">
				<h6><span class="glyphicon glyphicon-phone"></span> <b>Developers@PostCardCo.com</b></h6>
			</div>

		</div>
	</div>
	
</div>

app/views/static_pages/learn_more.html.erb
<div class="jumbotron shadow" style="background: linear-gradient(141deg, #0fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);">
	<div class="container">
		<h1 class="monter" style="color:white">Getting Started</h1>
		<h6>Basic Documentation to help you get started with Post Card Co</h6>
	</div>
</div>

<div class="container">
<h1 class="roboto">Lets Get Started!</h1>
<h6>Follow the sets to ensure proper card functionality.</h6>
	<div class="container">
		<h3 class="roboto"><span style="margin-right:5px" class="glyphicon glyphicon-upload"></span><b>Uploading</b> an Artwork</h3>
		<p>Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. </p>
		<br>
		<h3 class="roboto"><b>Using</b> an Artwork</h3>
		<p>Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. </p>
		<br>
		<h3 class="roboto"><b>Customizing</b> an Artwork</h3>
		<p>Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. </p>
		<br>
		<h3 class="roboto">Packaging Your Card</h3>
		<p>Semiotics paleo iPhone, pour-over williamsburg put a bird on it green juice street art locavore PBR&B. Cliche wolf kale chips kinfolk fingerstache XOXO. Vinyl art party vegan celiac, tote bag twee poutine pour-over. Lomo gochujang artisan sustainable cold-pressed, asymmetrical try-hard seitan flexitarian DIY authentic four dollar toast gluten-free. Meh microdosing cold-pressed chillwave. Letterpress locavore pinterest, tattooed four dollar toast pitchfork DIY ramps venmo mlkshk. </p>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron customheight shadow" style="padding-top:120px;">
<div class="container">
<% if @user.avatar.blank? %>
<h1 class="roboto white"><span class="glyphicon glyphicon-user"></span> <%= @user.first_name.titleize  %> <b><%= @user.last_name.titleize %></b></h1><br>
<% else %>
<h1 class="roboto white"><%= image_tag @user.avatar.url(:thumb), :class => 'shadow, img-thumbnail' %> <%= @user.first_name.titleize  %> <b><%= @user.last_name.titleize %></b></h1>
<% end %>
<h1 class="roboto">5,321</h1>
<h5><span class="glyphicon glyphicon-envelope"></span><%= @user.email %></h4>
<h5><%= @user.username %></h4>
<h5><%= @user.birthday%></h4>
<h5><span class="glyphicon glyphicon-time"><%= @user.last_sign_in_at %></h4>
<h5><%= @user.last_sign_in_ip %></h4>
</div>
</div>

<div class="container-fluid">
<div class="row">
<div class="col-sm-12 text-right">
	<div class="container">
		<button class="btn btn-primary btn-custom monter btn-lg" style="width:auto; height:40px;"><span class="glyphicon glyphicon-plus"></span> Follow <%= @user.first_name.titleize %></button>
		</div>
	</div>
<div class="col-md-2 col-sm-3">
	<div class="panel panel-default shadow">
		<div class="panel-heading"><h6>About <b><%= @user.first_name.titleize %></b></h6></div>
		<div class="panel-body" style="height:500px">
			<% if @user.about.blank? %>
			<p>I will fill this out later :).</p>
			<% else %>
			
			<p><%= @user.about %></p>
			<% end %>
		</div>
	</div>
</div>

<div class="col-sm-9 col-md-7">
	<div class="panel panel-default shadow">
	<div class="panel-heading">

	<h6 class="text-muted "><%= @user.first_name.titleize %>'s Contributions</h6></div>
	<div class="panel-body">
	<h6 class="text-muted roboto"><b><%= @user.first_name.titleize %></b> has <b><%= @user_artistuploads.count %></b> upload(s).</h6><hr>
	<% @user_artistuploads.each_slice(3) do |row| %>

		<div class="row">

		</div>
		<div class="panel-body">
		 
				<% row.each do |artistupload| %>
			<div class="col-sm-4">

				<div class="panel panel-default panel-bodycustom shadow">
				<div class="panel-heading roboto">
				<%= link_to artistupload.title, artistupload_path(artistupload) %>
				</div>
				<div class="panel-body panel-bodycustom">
				<%= image_tag artistupload.image.url(:medium), :class => 'img img-responsive' %>
				</div>
				</div>
			</div>
		<% end %>

		</div>
	
	<% end %>
	</div>
	</div>
</div>

</div>
</div>